### ISSUE TITLE
Switch to yarn?

### ISSUE THREAD

**Issue by peterbe** [developit/preact-boilerplate#143]
People who are using hot new tech like Preact will most likely be familiar with [yarn](https://yarnpkg.com/) by now.

**Comment by developit** [comment]
What would we be switching, just the docs?  I'd be a little hesitant to add a yarn lockfile to the repo since it would need constant updating.

**Comment by peterbe** [comment]
Well, first of all the README. 

I actually like the lockfile. It's my second favorite feature of yarn after speed. Makes things easier to avoid bugs in different environments. 
Besides, unlike `npm outdated` when you `yarn outdated` it just reports on packages in *your* `package.json`.

**Comment by developit** [comment]
I agree that lockfiles are good, just for a boilerplate where people expect to install and have relatively up-to-date dependencies out of the box, it's troublesome.  Perhaps a happy medium would be to list instructions for both `npm` and `yarn` in the readme?

**Comment by developit** [comment]
Closing for now - I don't think Yarn users really need dedicated instructions on how to use Yarn (it would be odd to intentionally switch package managers but not know how to install a dependency). The `npm run` steps don't really change with yarn since `run` is the same in both CLI's.  I'd be happy to merge a PR to add yarn to the docs, just not going to do it myself.

**Comment by peterbe** [comment]
I agree. When yarn came out I fell in love on the spot because I'm a speed freak. However, I later learned about [pnpm](https://pnpm.js.org/).
