### ISSUE TITLE
Add server side rendering example

### ISSUE THREAD

**Issue by ChrisCinelli** [developit/preact-boilerplate#67]

**Comment by developit** [comment]
Good idea!

**Comment by kuldeepkeshwar** [comment]
we can make a list of services which can behave differently on the server
like cookies, localStorage ...soon on, plus a way to split the build for server and client, same can be done for runtime also.

**Comment by developit** [comment]
I was thinking of using static-site-generator-webpack-plugin, since it does a lot of the mocking and stuff for us.

**Comment by kuldeepkeshwar** [comment]
what about the pages with dynamic content which need to be render on the server ?

**Comment by developit** [comment]
That's probably well beyond the scope of this boilerplate - usually people do prefetching to deal with that, which involves some sort of (centralized) state management system like Redux. This boilerplate intentionally does not include any of that since opinions and use-cases vary widely.

Personally, I'm not a huge fan of server-rendering dynamic content. I deploy all of my front-ends to a CDN, which means I actually do pre-rendering, not server-rendering, and the content must be static.  So I tend to just render the application shell and let the client do the data fetching.  It avoids a huge amount of complexity, and still achieves excellent performance results.

**Comment by lukeed** [comment]
@developit I'm with you; I do the same IRL but it's not always doable in all scenarios. 

For example, let's say you're building post templates for a blog. If you were to send a basic shell and _then_ initiate an API server query _then_ render the response, roughly half of active crawlers out there will either give up on you or stop after the seeing initial shell.

> My "half" is made-up, but there definitely is a noticeable hindrance in SEO crawling with CSR-only apps. It often feels more like two-thirds.

I think an example for SSR _is_ the way to go here -- not necessarily _here_; another repo would work. But having a set of guidelines is better than forcing everyone (especially beginners) fending for themselves. 

Personally, I've been playing with my own setup. Not really happy with anything yet. Truth is, I've waiting for an official Preact setup and/or [Next.js integration](https://github.com/zeit/next.js/pull/222).

**Comment by developit** [comment]
I have actually seen no penalty at all for fully client-side sites, so I no longer believe there is any SEO value in server-rendering. That said, if server-rendering were more or less a free perk, as is the case in Next.js, I'd certainly be a lot more open to doing it for no specific reason.

I still think deployments to a CDN can't be overlooked: there is lots of evidence showing that a fast-loading website improves search rankings, and hosting an entire frontend on a CDN in the best way I can think of to meet that mark.  It's also worth noting that server-rendering prevents (or breaks) a number of the better techniques used to produce responsive components - container queries, resize detection, render-on-visible, viewport-based paged rendering, etc.  To me, those are much too important to give up in order to get SSR working.

**Comment by lukeed** [comment]
I 100% agree. My only qualm is my experience I've had with ranking client side marketing pages.

The solution I came to was to just render the page text (and links) within a hidden div, then replace it as the app rendered. That way the old school crawlers had content and links to crawl.

I suppose this can continue on Twitter, if anything. Becoming less pertinent to this repo.

Especially now that the next.js PR merged!

**Comment by developit** [comment]
I'm going to close this out since I think it's out of scope for preact-boilerplate - there are a bunch of Preact SSR boilerplates now, and [preact-cli](https://github.com/developit/preact-cli) does prerendering out-of-the-box for those looking to go that route.
